name: weather_app
description: "A Weather App project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.3.3
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  get: ^4.6.6
  geolocator: ^9.0.2
  intl: ^0.18.1
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
  assets:
    - assets/icons/drawable-hdpi/
    - assets/icons/drawable-mdpi/
    - assets/icons/drawable-xhdpi/
    - assets/icons/drawable-xxhdpi/
    - assets/icons/drawable-xxxhdpi/
