name: weather_app
description: "A Weather App project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get: ^4.6.6
  dio: ^5.4.0
  permission_handler: ^10.2.0
  geolocator: ^10.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
  bloc_test: ^9.1.5

flutter:
  uses-material-design: true
  assets:
    - assets/icons/drawable-hdpi/
    - assets/icons/drawable-mdpi/
    - assets/icons/drawable-xhdpi/
    - assets/icons/drawable-xxhdpi/
    - assets/icons/drawable-xxxhdpi/
